apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  # annotations:
  #   kubernetes.io/service-account.name: "sa-name"
type: Opaque
data:
  mongo-root-username: bmN0aGFuaA==
  mongo-root-password: bmN0aGFuaA==
