version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_DATABASE=social-media-app
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    networks:
      - social_media_net
    volumes:
      # seeding scripts
      # - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_URL=mongodb://root:123456@mongo:27017/
    networks:
      - social_media_net
    depends_on:
      - mongo

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:

networks:
  social_media_net:
    driver: bridge
